#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : hacking
Version  : 1.1.0
Release  : 43
URL      : http://tarballs.openstack.org/hacking/hacking-1.1.0.tar.gz
Source0  : http://tarballs.openstack.org/hacking/hacking-1.1.0.tar.gz
Source1  : http://tarballs.openstack.org/hacking/hacking-1.1.0.tar.gz.asc
Summary  : OpenStack Hacking Guideline Enforcement
Group    : Development/Tools
License  : Apache-2.0
Requires: hacking-license = %{version}-%{release}
Requires: hacking-python = %{version}-%{release}
Requires: hacking-python3 = %{version}-%{release}
Requires: flake8
Requires: flake8-docstrings
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : eventlet-python
BuildRequires : flake8
BuildRequires : flake8-docstrings
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : reno-python
BuildRequires : six
BuildRequires : testrepository
BuildRequires : testrepository-python
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : virtualenv
Patch1: reqs.patch

%description
============

%package license
Summary: license components for the hacking package.
Group: Default

%description license
license components for the hacking package.


%package python
Summary: python components for the hacking package.
Group: Default
Requires: hacking-python3 = %{version}-%{release}

%description python
python components for the hacking package.


%package python3
Summary: python3 components for the hacking package.
Group: Default
Requires: python3-core

%description python3
python3 components for the hacking package.


%prep
%setup -q -n hacking-1.1.0
cd %{_builddir}/hacking-1.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576010642
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hacking
cp %{_builddir}/hacking-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/hacking/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hacking/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
